version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:${v}
    volumes:
      - ./wordpress-data:/var/www/html
    ports:
      - "6000:80"
    restart: always
    networks:
      - mynetwork
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  reverse-proxy:
    image: nginx:${v1}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    container_name: nginx-proxy
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - 80:80
    depends_on:
      - wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  mynetwork:
    driver: bridge
volumes:
  db-data:
  wordpress-data:
